language: rust

matrix:
  include:
  - os: linux
    rust: stable
    env: TARGET=x86_64-unknown-linux-gnu
  - os: linux
    rust: stable
    env: TARGET=i686-pc-windows-gnu
  #- os: linux
  #  rust: stable
  #  env: TARGET=x86_64-apple-darwin
  - os: linux
    rust: stable
    env: TARGET=i686-unknown-linux-gnu
  - os: osx
    rust: stable
    env: TARGET=x86_64-apple-darwin
  - os: windows
    rust: stable
    env: TARGET=x86_64-pc-windows-msvc

before_install:
- ci/install.sh "$TARGET"
install:
- rustup install "$TRAVIS_RUST_VERSION-$TARGET"
- rustup target add "$TARGET" || true
script:
- ci/build.sh
- ci/test.sh
